modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/wagyourtail/jsmacros"
license = "MPL-2.0"

[[mods]]
modId = "jsmacros"
version = "${version}"
displayName = "JS Macros"
authors = "Wagyourtail"
description = '''
    Macro Mod for Block Game
'''