# This is a basic workflow to help you get started with Actions

name: Build Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1_16_5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 1.16.5

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/github-script@v2
        id: fname
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/libs/${{ steps.fname.outputs.result }}.jar application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to curseforge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CF_API_KEY }}
          project_id: 403185
          game_endpoint: minecraft
          file_path: ./build/libs/${{ steps.fname.outputs.result }}.jar
          changelog: See the github release for changes.
          display_name: ${{ steps.fname.outputs.result }}
          game_versions: 70886:1.16.5,70886:1.16.4,70886:1.16.3,70886:1.16.2,2:Java 8,68441:Fabric
          release_type: release
          relations: modmenu:optionalDependency
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fname.outputs.result }}
          path: ./build/libs/*

  build-1_16_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: backport-1.16.1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/github-script@v2
        id: fname
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/libs/${{ steps.fname.outputs.result }}.jar application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fname.outputs.result }}
          path: ./build/libs/*

  build-1_15_2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: backport-1.15.2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/github-script@v2
        id: fname
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/libs/${{ steps.fname.outputs.result }}.jar application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to curseforge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CF_API_KEY }}
          project_id: 403185
          game_endpoint: minecraft
          file_path: ./build/libs/${{ steps.fname.outputs.result }}.jar
          changelog: See the github release for changes.
          display_name: ${{ steps.fname.outputs.result }}
          game_versions: 68722:1.15.2,2:Java 8,68441:Fabric
          release_type: release
          relations: modmenu:optionalDependency
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fname.outputs.result }}
          path: ./build/libs/*

  build-1_14_4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: backport-1.14.4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/github-script@v2
        id: fname
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/libs/${{ steps.fname.outputs.result }}.jar application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to curseforge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CF_API_KEY }}
          project_id: 403185
          game_endpoint: minecraft
          file_path: ./build/libs/${{ steps.fname.outputs.result }}.jar
          changelog: See the github release for changes.
          display_name: ${{ steps.fname.outputs.result }}
          game_versions: 64806:1.14.4,2:Java 8,68441:Fabric
          release_type: release
          relations: modmenu:optionalDependency
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fname.outputs.result }}
          path: ./build/libs/*
  
  build-forge-1_16_5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: forge-1.16.5

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/github-script@v2
        id: fname
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/libs/${{ steps.fname.outputs.result }}.jar application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to curseforge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CF_API_KEY }}
          project_id: 403185
          game_endpoint: minecraft
          file_path: ./build/libs/${{ steps.fname.outputs.result }}.jar
          changelog: See the github release for changes.
          display_name: ${{ steps.fname.outputs.result }}
          game_versions: 70886:1.16.5,70886:1.16.4,70886:1.16.3,2:Java 8,7498:Forge
          release_type: release
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fname.outputs.result }}
          path: ./build/libs/*
  
  build-1_8_9:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: backport-1.8.9

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/github-script@v2
        id: fname
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/libs/${{ steps.fname.outputs.result }}.jar application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to curseforge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CF_API_KEY }}
          project_id: 403185
          game_endpoint: minecraft
          file_path: ./build/libs/${{ steps.fname.outputs.result }}.jar
          changelog: See the github release for changes.
          display_name: ${{ steps.fname.outputs.result }}
          game_versions: 5806:1.8.9,2:Java 8,7498:Forge
          release_type: release
          relations: modmenu:optionalDependency
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fname.outputs.result }}
          path: ./build/libs/*
