on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      game_vers:
        required: true
        type: string
      java_vers:
        required: true
        type: string
    secrets:
      CF_API_KEY:
        required: true
      MODRINTH_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.branch }}

      - name: Check For Fabric Jar
        uses: actions/github-script@v5
        id: fabric_release
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && !e.endsWith("shadow.jar") && e.endsWith(".jar") && e.includes("FABRIC"))[0] || false;

      - name: Upload Fabric to Git Release
        if: ${{ steps.fabric_release.outputs.result != 'false' }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./${{ steps.fabric_release.outputs.result }} application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check For Forge Jar
        uses: actions/github-script@v5
        id: forge_release
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("./").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && !e.endsWith("shadow.jar") && e.endsWith(".jar") && e.includes("FORGE"))[0] || false;

      - name: Upload Forge to Git Release
        if: ${{ steps.forge_release.outputs.result != 'false' }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./${{ steps.forge_release.outputs.result }} application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip TS
        uses: vimtor/action-zip@v1
        with:
          files: typescript/
          dest: typescript-${{ inputs.branch }}.zip

      - name: Upload TS to Git Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./typescript-${{ inputs.branch }}.zip application/jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Version Number
        uses: actions/github-script@v5
        id: version_num
        env:
          GV: '${{ inputs.game_vers }}'
          REF: '${{ GITHUB_REF }}'
        with:
          result-encoding: string
          script: |
            return `${process.env.GV.split(" ")[0]}-${process.env.REF.split('/')[2]}`

      - name: Run Publish Fabric
        if: ${{ steps.fabric_release.outputs.result != 'false' }}
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: 3wGWhm8A
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 403185
          curseforge-token: ${{ secrets.CF_API_KEY }}

          name: ${{ steps.fabric_release.outputs.result }}
          version: ${{ steps.version_num.outputs.result }}-fabric

          files: ./${{ steps.fabric_release.outputs.result }}
          version-type: release

          loaders: fabric
          game-versions: ${{ inputs.game_vers }}

          java: ${{ inputs.java_vers }}
          retry-attempts: 5
          retry-delay: 60000

      - name: Run Publish Forge
        if: ${{ steps.forge_release.outputs.result != 'false' }}
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: 3wGWhm8A
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 403185
          curseforge-token: ${{ secrets.CF_API_KEY }}

          name: ${{ steps.forge_release.outputs.result }}
          version: ${{ steps.version_num.outputs.result }}-forge

          files: ./${{ steps.forge_release.outputs.result }}
          version-type: release

          loaders: forge
          game-versions: ${{ inputs.game_vers }}

          java: ${{ inputs.java_vers }}
          retry-attempts: 5
          retry-delay: 60000
