# This is a basic workflow to help you get started with Actions

name: Build Release V2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

jobs:
  build_1_18:
    uses: wagyourtail/jsmacros/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: main-1.18
      java_version: 17

  build_1_17:
    uses: wagyourtail/jsmacros/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: backport-1.17.1
      java_version: 17

  build_1_16:
    uses: wagyourtail/jsmacros/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: backport-1.16.5
      java_version: 17

  build_1_15:
    uses: wagyourtail/jsmacros/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: backport-1.15.2
      java_version: 17

  build_1_14:
    uses: wagyourtail/jsmacros/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: backport-1.14.4
      java_version: 17

  build_1_8:
    uses: wagyourtail/jsmacros/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: backport-1.8.9
      java_version: 8

  deploy_1_18:
    uses: wagyourtail/jsmacros/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: main-1.18
      cf_data_fabric: 73250:1.18.2,2:Java 17,68441:Fabric
      cf_data_forge: 73250:1.18.2,2:Java 17,7498:Forge
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    needs:
      - build_1_18
      - deploy_1_17
      - upload_pydoc

  deploy_1_17:
    uses: wagyourtail/jsmacros/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: backport-1.17.1
      cf_data_fabric: 73242:1.17.1,2:Java 16,68441:Fabric
      cf_data_forge: 73242:1.17.1,2:Java 16,7498:Forge
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    needs:
      - build_1_17
      - deploy_1_16

  deploy_1_16:
    uses: wagyourtail/jsmacros/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: backport-1.16.5
      cf_data_fabric: 70886:1.16.5,70886:1.16.4,70886:1.16.3,2:Java 8,68441:Fabric
      cf_data_forge: 70886:1.16.5,70886:1.16.4,70886:1.16.3,2:Java 8,7498:Forge
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    needs:
      - build_1_16
      - deploy_1_15

  deploy_1_15:
    uses: wagyourtail/jsmacros/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: backport-1.15.2
      cf_data_fabric: 68722:1.15.2,2:Java 8,68441:Fabric
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    needs:
      - build_1_15
      - deploy_1_14

  deploy_1_14:
    uses: wagyourtail/jsmacros/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: backport-1.14.4
      cf_data_fabric: 64806:1.14.4,2:Java 8,68441:Fabric
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    needs:
      - build_1_14
      - deploy_1_8

  deploy_1_8:
    uses: wagyourtail/jsmacros/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: backport-1.8.9
      cf_data_fabric: 68722:1.8.9,2:Java 8,68441:Fabric
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    needs:
      - build_1_8


  upload_pydoc:
    runs-on: ubuntu-latest
    needs:
      - build_1_18
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: main-1.18
          path: dist

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python Deps
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine


      - name: Upload PyDoc
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py dist bdist_wheel
          twine upload dist/*
        working-directory: python
