# This is a basic workflow to help you get started with Actions

name: Build Release V2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

jobs:

  build_1_19:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: main-1.19
      java_version: 17

  build_1_18:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: backport-1.18.2
      java_version: 17

  build_1_17:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: backport-1.17.1
      java_version: 17

  build_1_16:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: backport-1.16.5
      java_version: 17

  build_1_15:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: backport-1.15.2
      java_version: 17

  build_1_14:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: backport-1.14.4
      java_version: 17

  build_1_12:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: backport-1.12.2
      java_version: 17

  build_1_8:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: backport-1.8.9
      java_version: 8

  deploy_1_19:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: main-1.19
      game_vers: 1.19
      java_vers: 17
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_19
      - deploy_1_18

  deploy_1_18:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: backport-1.18.2
      game_vers: 1.18.2
      java_vers: 17
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_18
      - deploy_1_17

  deploy_1_17:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: backport-1.17.1
      game_vers: 1.17.1
      java_vers: 16
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_17
      - deploy_1_16

  deploy_1_16:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: backport-1.16.5
      game_vers: |
        1.16.5
        1.16.4
        1.16.3
      java_vers: 8
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_16
      - deploy_1_15

  deploy_1_15:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: backport-1.15.2
      game_vers: 1.15.2
      java_vers: 8
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_15
      - deploy_1_14

  deploy_1_14:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: backport-1.14.4
      game_vers: 1.14.4
      java_vers: 8
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_14
      - deploy_1_12

  deploy_1_12:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: backport-1.12.2
      game_vers: 1.12.2
      java_vers: 8
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_12
      - deploy_1_8

  deploy_1_8:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: backport-1.8.9
      game_vers: 1.8.9
      java_vers: 8
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_8


  upload_pydoc:
    runs-on: ubuntu-latest
    needs:
      - build_1_19
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: main-1.19
          path: dist

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python Deps
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Upload PyDoc
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd dist/python
          python setup.py sdist bdist_wheel
          twine upload dist/*

  publish_npm:
    runs-on: ubuntu-latest
    needs:
      - build_1_19
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: main-1.19
          path: dist

      - uses: actions/setup-node@v3
        name: Setup node
        with:
          registry-url: https://registry.npmjs.org/
          node-version: latest

      - name: Extract Version Number
        uses: actions/github-script@v5
        id: version_num
        env:
          REF: '${{ github.ref }}'
        with:
          result-encoding: string
          script: |
            return `${process.env.REF.replace(/\/?refs\/tags\//, '')}`

      # The types .d.ts file normally has a version number in it
      # This is useful for people using the file directly so they can download multiple versions and keep track of which one is which
      # But for the npm package, it's easier to rename it to be consistent than to dynamically edit the package.json and tsconfig.json
      - name: Remove version number from .d.ts file
        run:
          mv dist/typescript/headers/JsMacros-*.d.ts dist/typescript/headers/JsMacros.d.ts

      - name: Publish to node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/typescript
          npm version ${{ steps.version_num.outputs.result }}
          npm publish

